### ISSUE TITLE
how can I clone this and run it myself?

### ISSUE THREAD

**Issue by charpty** [ceph/ceph-autotests#1]
could someone tell me how can I build a server to run this in my office?
I already have a teuthology platform in my office.

**Comment by jdurgin** [comment]
This is obsolete - it was replaced by https://github.com/ceph/teuthology and https://github.com/ceph/ceph-qa-suite

**Comment by charpty** [comment]
ok,  I know,  but teuthology just can use in terminal,  how can I use teutholoy in browser?
